name: build
on:
  pull_request:
    paths:
      - '!**'
      - '.github/workflows/build.yml'
      - 'Makefile'
      - 'hackernews.el'
  push:
    paths:
      - '!**'
      - '.github/workflows/build.yml'
      - 'Makefile'
      - 'hackernews.el'
permissions: {}
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 23.4
          - 24.1
          - 24.2
          - 24.3
          - 24.4
          - 24.5
          - 25.1
          - 25.2
          - 25.3
          - 26.1
          - 26.2
          - 26.3
          - 27.1
          - 27.2
          - 28.1
          - 28.2
          - 29.1
          - 29.2
          - 29.3
          - 29.4
          - 30.1
          - release-snapshot
          - snapshot
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - name: Byte-compile
      run: make
